import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '~/components/Header';
import Top from '~/components/Top';
import About from '~/components/About';
import HairCatalog from '~/components/HairCatalog';
import Menu from '~/components/Menu';
import ReserveButton from '~/components/ReserveButton';
import Staff from '~/components/Staff';
import Footer from '~/components/Footer';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Top />
        <About />
        <HairCatalog />
        <Menu />
        <Staff />
        <Footer />
        <ReserveButton />
      </main>
    </div>
  );
};

export default Home;
